version: "3.7"

services:
#  backend:
#    build:
#        dockerfile: Dockerfile
#        context: ./packages/backend
#        target: development
#    command: npm run dev
#    env_file:
#      - ./packages/backend/.env
#    environment:
#      POSTGRES_HOST: db
#    volumes:
#      - .:/usr/src/
#      - /usr/app/node_modules
#    ports:
#      - ${PORT}:${PORT}
##      - 9229:9229
#    depends_on:
#      - db
  db:
    image: postgres:14
    restart: always
    env_file:
      - ./packages/backend/.env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./db/pgData:/var/lib/postgresql/data


  redis:
    image: redis:latest
    ports:
      - 6379:6379
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis-data:/data
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - HTTP_USER=root
      - HTTP_PASSWORD=qwerty
    ports:
      - 8081:8081
    depends_on:
      - redis

volumes:
  redis-data: